apiVersion: v1
kind: Service
metadata:
  name: azure-files-nginx-service
  labels: 
    app: azure-files-nginx-app
spec:
  selector:
    app: azure-files-nginx-app
  ports: 
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: azure-files-nginx-deployment
  labels:
    app: azure-files-nginx-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: azure-files-nginx-app
  template:  
    metadata:
      labels: 
        app: azure-files-nginx-app
    spec:
      containers:
        - name: azure-files-nginx-app
          image: predictram.azurecr.io/predictram/frontend
          imagePullPolicy: Always
          ports: 
            - containerPort: 80         
          volumeMounts:
            - name: events
              mountPath: "/usr/share/nginx/html/uploaded/static/"
      volumes:
        - name: events
          persistentVolumeClaim:
            claimName: predictramfile-pvc   