export const stockAnalysisConfig = [
  { key: "Stock Symbol", label: "Stock Symbol" },
  { key: "Volatility", label: "Volatility" },
  { key: "Beta", label: "Beta" },
  { key: "Return_on_Investment", label: "Return on Investment" },
  { key: "CAGR", label: "CAGR" },
  { key: "Debt_to_Equity_Ratio", label: "Debt to Equity Ratio" },
  { key: "Latest_Close_Price", label: "Latest Close Price" },
  { key: "P/E_Ratio", label: "P/E Ratio" },
  { key: "P/B_Ratio", label: "P/B Ratio" },
  { key: "EPS", label: "EPS" },
  { key: "Dividend_Yield", label: "Dividend Yield" },
  { key: "Market_Cap", label: "Market Cap" },
  { key: "Fifty_MA", label: "50-Day Moving Average" },
  { key: "Two_Hundred_MA", label: "200-Day Moving Average" },
  { key: "RSI", label: "RSI" },
  { key: "MACD", label: "MACD" },
  { key: "Bollinger_Band", label: "Bollinger Band" },
  { key: "Current_Price", label: "Current Price" },
  { key: "Percentage_Difference", label: "Percentage Difference" },
  { key: "Correlation_with_event", label: "Correlation with Event" },
  { key: "Category", label: "Category" },
  { key: "Total_Score", label: "Total Score" },
  { key: "Stock Industry", label: "Stock Industry" },
  { key: "Dividend Payout Ratio", label: "Dividend Payout Ratio" },
  {
    key: "Five Year Avg Dividend Yield",
    label: "Five Year Avg Dividend Yield",
  },
  {
    key: "Price to Sales Trailing 12 Months",
    label: "Price to Sales Trailing 12 Months",
  },
  {
    key: "Trailing Annual Dividend Rate",
    label: "Trailing Annual Dividend Rate",
  },
  { key: "Profit Margins", label: "Profit Margins" },
  { key: "% Held by Insiders", label: "% Held by Insiders" },
  { key: "% Held by Institutions", label: "% Held by Institutions" },
  { key: "Volume", label: "Volume" },
  { key: "Regular Market Volume", label: "Regular Market Volume" },
  { key: "Average Volume", label: "Average Volume" },
  { key: "Average Volume 10 days", label: "Average Volume 10 days" },
  { key: "Average Daily Volume 10 Day", label: "Average Daily Volume 10 Day" },
  { key: "Return on Assets (ttm)", label: "Return on Assets (ttm)" },
  { key: "Return on Equity (ttm)", label: "Return on Equity (ttm)" },
  { key: "Correlation with ^NSEI", label: "Correlation with ^NSEI" },
  { key: "Annualized Alpha (%)", label: "Annualized Alpha (%)" },
  { key: "Annualized Volatility (%)", label: "Annualized Volatility (%)" },
  { key: "Sharpe Ratio", label: "Sharpe Ratio" },
  { key: "Treynor Ratio", label: "Treynor Ratio" },
  { key: "Sortino Ratio", label: "Sortino Ratio" },
  { key: "Maximum Drawdown", label: "Maximum Drawdown" },
  { key: "R-Squared", label: "R-Squared" },
  { key: "Downside Deviation", label: "Downside Deviation" },
  {
    key: "Annualized Tracking Error (%)",
    label: "Annualized Tracking Error (%)",
  },
  { key: "VaR (95%)", label: "VaR (95%)" },
  { key: "50-Day Moving Average", label: "50-Day Moving Average" },
  { key: "200-Day Moving Average", label: "200-Day Moving Average" },
  {
    key: "Correlation with ^NSEI Interpretation",
    label: "Correlation with ^NSEI Interpretation",
  },
  {
    key: "Annualized Alpha (%) Interpretation",
    label: "Annualized Alpha (%) Interpretation",
  },
  {
    key: "Annualized Volatility (%) Interpretation",
    label: "Annualized Volatility (%) Interpretation",
  },
  { key: "Sharpe Ratio Interpretation", label: "Sharpe Ratio Interpretation" },
  {
    key: "Treynor Ratio Interpretation",
    label: "Treynor Ratio Interpretation",
  },
  {
    key: "Sortino Ratio Interpretation",
    label: "Sortino Ratio Interpretation",
  },
  {
    key: "Maximum Drawdown Interpretation",
    label: "Maximum Drawdown Interpretation",
  },
  { key: "R-Squared Interpretation", label: "R-Squared Interpretation" },
  {
    key: "Downside Deviation Interpretation",
    label: "Downside Deviation Interpretation",
  },
  {
    key: "Annualized Tracking Error (%) Interpretation",
    label: "Annualized Tracking Error (%) Interpretation",
  },
  { key: "VaR (95%) Interpretation", label: "VaR (95%) Interpretation" },
  { key: "industry", label: "Industry" },
  { key: "sector", label: "Sector" },
  { key: "exDividendDate", label: "Ex-Dividend Date" },
  { key: "payoutRatio", label: "Payout Ratio" },
  { key: "fiveYearAvgDividendYield", label: "Five Year Avg Dividend Yield" },
  { key: "beta", label: "Beta" },
  { key: "volume", label: "Volume" },
  { key: "regularMarketVolume", label: "Regular Market Volume" },
  { key: "averageVolume", label: "Average Volume" },
  { key: "averageVolume10days", label: "Average Volume 10 days" },
  { key: "averageDailyVolume10Day", label: "Average Daily Volume 10 Day" },
  { key: "marketCap", label: "Market Cap" },
  { key: "fiftyTwoWeekLow", label: "52-Week Low" },
  { key: "fiftyTwoWeekHigh", label: "52-Week High" },
  {
    key: "priceToSalesTrailing12Months",
    label: "Price to Sales Trailing 12 Months",
  },
  { key: "fiftyDayAverage", label: "50-Day Average" },
  { key: "twoHundredDayAverage", label: "200-Day Average" },
  { key: "trailingAnnualDividendRate", label: "Trailing Annual Dividend Rate" },
  {
    key: "trailingAnnualDividendYield",
    label: "Trailing Annual Dividend Yield",
  },
  { key: "enterpriseValue", label: "Enterprise Value" },
  { key: "profitMargins", label: "Profit Margins" },
  { key: "floatShares", label: "Float Shares" },
  { key: "sharesOutstanding", label: "Shares Outstanding" },
  { key: "heldPercentInsiders", label: "Held Percent by Insiders" },
  { key: "heldPercentInstitutions", label: "Held Percent by Institutions" },
  { key: "impliedSharesOutstanding", label: "Implied Shares Outstanding" },
  { key: "bookValue", label: "Book Value" },
  { key: "priceToBook", label: "Price to Book" },
  { key: "netIncomeToCommon", label: "Net Income to Common" },
  { key: "trailingEps", label: "Trailing EPS" },
  { key: "lastSplitFactor", label: "Last Split Factor" },
  { key: "lastSplitDate", label: "Last Split Date" },
  { key: "enterpriseToRevenue", label: "Enterprise to Revenue" },
  { key: "enterpriseToEbitda", label: "Enterprise to EBITDA" },
  { key: "totalCash", label: "Total Cash" },
  { key: "totalCashPerShare", label: "Total Cash Per Share" },
  { key: "ebitda", label: "EBITDA" },
  { key: "totalDebt", label: "Total Debt" },
  { key: "quickRatio", label: "Quick Ratio" },
  { key: "currentRatio", label: "Current Ratio" },
  { key: "totalRevenue", label: "Total Revenue" },
  { key: "debtToEquity", label: "Debt to Equity" },
  { key: "revenuePerShare", label: "Revenue Per Share" },
  { key: "returnOnAssets", label: "Return on Assets" },
  { key: "returnOnEquity", label: "Return on Equity" },
  { key: "freeCashflow", label: "Free Cashflow" },
  { key: "operatingCashflow", label: "Operating Cashflow" },
  { key: "revenueGrowth", label: "Revenue Growth" },
  { key: "grossMargins", label: "Gross Margins" },
  { key: "ebitdaMargins", label: "EBITDA Margins" },
  { key: "operatingMargins", label: "Operating Margins" },
  { key: "trailingPegRatio", label: "Trailing PEG Ratio" },
  { key: "forwardPE", label: "Forward P/E" },
  { key: "trailingPE", label: "Trailing P/E" },
  { key: "industry_forwardPE", label: "Industry Forward P/E" },
  { key: "industry_trailingPE", label: "Industry Trailing P/E" },
  { key: "industry_debtToEquity", label: "Industry Debt to Equity" },
  { key: "industry_currentRatio", label: "Industry Current Ratio" },
  { key: "industry_quickRatio", label: "Industry Quick Ratio" },
  { key: "industry_ebitda", label: "Industry EBITDA" },
  { key: "industry_totalDebt", label: "Industry Total Debt" },
  { key: "industry_returnOnAssets", label: "Industry Return on Assets" },
  { key: "industry_returnOnEquity", label: "Industry Return on Equity" },
  { key: "industry_revenueGrowth", label: "Industry Revenue Growth" },
  { key: "industry_grossMargins", label: "Industry Gross Margins" },
  { key: "industry_ebitdaMargins", label: "Industry EBITDA Margins" },
  { key: "industry_operatingMargins", label: "Industry Operating Margins" },
];
